title: "LOUMACHI Abderrahmane Anis"
email: anisrt72@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hello, this is my Github page used for LHD Build.
baseurl: "/" 
url: "https://anisloum.github.io" 
twitter_username: mlhacks
github_username: anisloum

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
